exception: handle sd_bus_error ownership properly
An earlier commit attempted to fix a use-after-free but in doing so
introduced a memory leak in many error handling paths.  The SdBusError
constructor has a comment indicating that the SdBusError is supposed to
take ownership of the error; the previous commit undid that ownership
transfer and attempted to use `sd_bus_error_copy` to create a new copy.
This is not the documented behavior of SdBusError and is now reverted.

The earlier commit was trying to fix a use-after-free case which
happened to only be in a single code path used in async clients.  When
`sd_bus_message_get_error` (or sdbusplus equivalent) is used, the
message maintains ownership of the error and simply adjusting pointers
does not change that.  In the code path we need to create a new / copy
of the error so that we can transfer ownership properly into the
SdBusError class.

Fixes: 8017aca7d579 ("exception: fix use-after-free")
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Ibf49aae7a81a929f992b82fc0e8ef86b764b319c
(cherry picked from commit 54d3b98e3c0d3dfbdd68a23cffe4de039548f337)